//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangOut.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Id { get; set; }
        public Nullable<int> PlaceId { get; set; }
        public string UserId { get; set; }
        public System.DateTime CheckinDate { get; set; }
        public Nullable<System.DateTime> CheckoutDate { get; set; }
        public Nullable<int> NumberOfChildren { get; set; }
        public Nullable<int> NumberOfAdults { get; set; }
        public Nullable<int> NumberOfRooms { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Place Place { get; set; }
    }
}
