//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangOut.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transport
    {
        public int Id { get; set; }
        public int TransType { get; set; }
        public int DepartureFrom { get; set; }
        public int DepartureTo { get; set; }
        public string Time { get; set; }
    
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
        public virtual TransportType TransportType { get; set; }
    }
}
